### ISSUE TITLE
div. initialfehler

### ISSUE THREAD

**Issue by gitalexa** [unl0ck/viessmann_gridbox_hack#1]
Moin. Danke für den Hack! Leider bin ich mit python auf kriegsfuss und erhalte:
---
/usr/local/bin/python2.7 /Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py
Traceback (most recent call last):
  File "/Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py", line 53, in <module>
    GridboxConnector(data).retrieve_live_data()
  File "/Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py", line 24, in __init__
    self.get_token()
  File "/Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py", line 31, in get_token
    self.id_token = response_json["id_token"]
KeyError: 'id_token'

Process finished with exit code 1
----

Client-ID habe ich hier her:
https://app.developer.viessmann.com/

und user und pw das genommen, womit ich mich da anmelden kann.

**Comment by unl0ck** [comment]
Ja ich würde dir ein Update auf Python 3.9+ raten Mit Freundlichen GrüßenSimon HelmingOn 20. Jul 2023, at 17:28, Alexander Probst ***@***.***> wrote:﻿
Moin. Danke für den Hack! Leider bin ich mit python auf kriegsfuss und erhalte:
/usr/local/bin/python2.7 /Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py
Traceback (most recent call last):
File "/Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py", line 53, in 
GridboxConnector(data).retrieve_live_data()
File "/Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py", line 24, in init
self.get_token()
File "/Users/alex/PycharmProjects/viessmann_gridbox_hack/read_live_data.py", line 31, in get_token
self.id_token = response_json["id_token"]
KeyError: 'id_token'
Process finished with exit code 1
Client-ID habe ich hier her:
https://app.developer.viessmann.com/
und user und pw das genommen, womit ich mich da anmelden kann.

**Comment by unl0ck** [comment]
Python 3.9+ sollte helfen und Client id sollte die passen die drin war, brauchst eigentlich nur email und dein Passwort

**Comment by gitalexa** [comment]
leider nicht. python 3.10 gibt

-> hier: response_json = response.json()
mit -> print (response_json)

{'error': 'invalid_grant', 'error_description': 'Wrong email or password.'}

in der config hab ich die Daten eingetragen, mit denen ich mich hier: https://developer.viessmann.com/ anmelde

ich rufe es mit python3.10 main.py auf und erhalte:

(venv)  ✘ alex  ~/PycharmProjects/viessmann_grid  python3.10 main.py
{'error': 'invalid_grant', 'error_description': 'Wrong email or password.'}
Traceback (most recent call last):
  File "/Users/alex/PycharmProjects/viessmann_grid/main.py", line 54, in <module>
    GridboxConnector(data).retrieve_live_data()
  File "/Users/alex/PycharmProjects/viessmann_grid/main.py", line 23, in __init__
    self.get_token()
  File "/Users/alex/PycharmProjects/viessmann_grid/main.py", line 32, in get_token
    self.id_token = response_json["id_token"]
KeyError: 'id_token'

**Comment by unl0ck** [comment]
du musst hier dein username und password nehmen die du nutzt um auf das Dashboard von https://mygridbox.viessmann.com/login

**Comment by gitalexa** [comment]
danke! Wichtiger Hinweis... Wenn Du willst, kannst Du mir hier im Projekt Rechte einräumen, dann würde ich das dokumentieren...

hab auch für das jsonresult klassen erstellt. soll ich einen fork machen oder hier einchecken?

**Comment by unl0ck** [comment]
Ich schau mal wie das geht.
Hat sich dein Problem nun erledigt?

**Comment by gitalexa** [comment]
ja. läuft prima!

(im Repository unter Settings mich bei Collaborateur eintragen)
